apiVersion: v1
kind: Template
metadata:
  name: image-scanning-request-template
  annotations:
    openshift.io/display-name: Image Scanning Request Template
    description: Template to create an Image Scanning Request
objects:
- apiVersion: "cop.redhat.com/v1alpha2"
  kind: ImageScanningRequest
  metadata:
    name: ${IMAGE_SCANNING_REQUEST_NAME}
  spec:
    imageStreamTag: "${IMAGE_STREAM_TAG}"
parameters:
- name: IMAGE_SCANNING_REQUEST_NAME
  displayName: Image Scanning Request Name
  description: Name of the Image Scanning Request
  required: true
- description: ImageStream Tag of the Image to Scan (Format is <imagestream>:<tag>)
  displayName: ImageStream Tag
  name: IMAGE_STREAM_TAG
  required: true
