apiVersion: v1
kind: Template
metadata:
  name: image-scanning-signing-service-
  annotations:
    openshift.io/display-name: Image Scanning Signing Service
    description: Template to create the Image Scanning Signing Service Application
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        containers:
        - image: ${APPLICATION_NAME}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        restartPolicy: Always
        serviceAccount: ${SERVICE_ACCOUNT}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange

parameters:
- name: APPLICATION_NAME
  displayName: Name
  description: Name Applied to the Resulting ImageStream and BuildConfig
  value: image-scanning-signing-service
  required: true
- description: Service Account to Run the Application
  displayName: Service Account
  name: SERVICE_ACCOUNT
  required: true
  value: imagemanager